### ISSUE TITLE
Console Output

### ISSUE THREAD

**Issue by PanzerStras** [EricZimmerman/MFTECmd#27] opened 2024-11-06 08:42 UTC
Hello Eric,

I'm working on a Windows 11 system and have noticed that some files in the MFT contain commas in their names, which can cause parsing issues with comma-separated values (CSV) files. To handle this, I've modified the delimiter to a tab (Delimiter = "\t"), which should help avoid any conflicts.

Additionally, I'd like to ask if there’s a way to output the data to the console instead of generating a CSV file. This would simplify my workflow, especially for quick data checks.

Thanks in advance for any insights or suggestions!

Best regards,

Quentin

**Comment by EricZimmerman** [comment] 2024-11-06 12:58
it should not, if you are using an RFC compliant parser. i generate compliant csvs

so the question is, what are you using to parse the files?

**Comment by EricZimmerman** [comment] 2024-11-06 14:50
closing until we get more detail, but if this was an issue. TLE wouldnt work.

the problem is using a non-RFC compliant CSV parser.

you cannot do something like

line.split(",") 

and expect it to work

**Closed by EricZimmerman** 2024-11-06 14:50 UTC
